### ISSUE TITLE
Error load Framework

### ISSUE THREAD

**Issue by burdzand** [RadiusNetworks/swift-framework-example#1]
Hi code but I'm having a problem when I run on any device.

dyld: Library not loaded: @rpath/SimpleFramework.framework/SimpleFramework
  Referenced from: /var/mobile/Containers/Bundle/Application/379B410B-0CEC-4E71-91C2-46D76AA03F77/SwiftApp.app/SwiftApp
  Reason: no suitable image found.  Did find:

**Comment by eonist** [comment]
Can't get this to work either.

**Comment by bennokress** [comment]
If you should still have this issue then here is your solution: Turn on "Always Embed Swift Standard Libraries" in the Build Settings of your App Target (not Framework Target!). This is the equivalent to step 3 of the section "Consuming the Framework from an Objective-C app" of this tutorial which is deprecated since Xcode 8.

**Comment by eonist** [comment]
I figured it out. thx
